### ISSUE TITLE
Ambiguity in the README "replace "KCP" with "FizzySteamworks"

### ISSUE THREAD

**Issue by trueivorian** [Chykary/FizzySteamworks#38]
Step 2 in the README asks to replace "KCP" with "FizzySteamworks" in the NetworkManager, however the only reference to KCP in NetworkManager.cs is `using kcp2k;` and replacing this line with `using FizzySteamworks;` generates an error.

**Comment by LukeSeers** [comment]
Fyi I have not touched this in a long while, but yea the readme for FizzySteamworks as gotten very bloated by the seams of things from past contributors. Can't lie, kinda annoys me since I tried to keep it simple and clean.

Anyway, you should have an object in your scene with the script `NetworkManager` attached to it.

If the `KCP Transport` gets added, remove the `KCP Transport` and add the `FizzySteamworks Transport` instead. Make sure in the `NetworkManager` you have link the `FizzySteamworks Transport` script in it too.
