### ISSUE TITLE
CS7036 Errors after import

### ISSUE THREAD

**Issue by Datertec** [Chykary/FizzySteamworks#47]
Hi,

I have just imported mirror into my project and imported the Fizzy Steam works file however I get the below errors (I have not changed anything)

`Assets\Mirror\Runtime\Transport\FizzySteamworks\LegacyServer.cs(27,71): error CS7036: There is no argument given that corresponds to the required formal parameter 'arg3' of 'Action<int, TransportError, string>.Invoke(int, TransportError, string)'`

`Assets\Mirror\Runtime\Transport\FizzySteamworks\NextServer.cs(42,71): error CS7036: There is no argument given that corresponds to the required formal parameter 'arg3' of 'Action<int, TransportError, string>.Invoke(int, TransportError, string)'`

Any idea why these error are coming up?

**Comment by lukasIguess-dev** [comment]
Its the same for me!
I'm using unity 2021.3.22f1 so it might be the reason for these errors
I suggest trying either the now latest version of unity or an older version.

**Comment by AbdrahmanSoliman** [comment]
I faced the same issue. In order to fix it, firstly make sure you’re using the latest version of Steamworks by opening package manager -> Add package from git URL ->“[https://github.com/Chykary/FizzySteamworks.git?path=/com.mirror.steamworks.net](https://edgeservices.bing.com/edgesvc/url)” 

Then head to the releases page of Steamworks.NET ([https://github.com/rlabrecque/Steamworks.NET/releases](https://edgeservices.bing.com/edgesvc/url)). From the latest release, copy the Unity Package Manager URL and add it to your package manager as well. Right now, the latest version URL is “[https://github.com/rlabrecque/Steamworks.NET.git?path=/com.rlabrecque.steamworks.net#20.2.0](https://edgeservices.bing.com/edgesvc/url)”. Most probably there will be a newer version that’s why I told you to head to their releases page.

Hopefully this fixes your errors!

**Comment by ErencanPelin** [comment]
> I faced the same issue. In order to fix it, firstly make sure you’re using the latest version of Steamworks by opening package manager -> Add package from git URL ->“[https://github.com/Chykary/FizzySteamworks.git?path=/com.mirror.steamworks.net](https://edgeservices.bing.com/edgesvc/url)”
> 
> Then head to the releases page of Steamworks.NET ([https://github.com/rlabrecque/Steamworks.NET/releases](https://edgeservices.bing.com/edgesvc/url)). From the latest release, copy the Unity Package Manager URL and add it to your package manager as well. Right now, the latest version URL is “[https://github.com/rlabrecque/Steamworks.NET.git?path=/com.rlabrecque.steamworks.net#20.2.0](https://edgeservices.bing.com/edgesvc/url)”. Most probably there will be a newer version that’s why I told you to head to their releases page.
> 
> Hopefully this fixes your errors!

I followed these steps, but still couldn't get it to work:

After adding the packages via the package manager, of course the packages go to the Packages folder which is okay, but packages there don't show up errors in console. The scripts are still bugged for some reason though, missing overrides etc because you're not actually able to add them onto any gameObjects or anything
